### ISSUE TITLE
Does Python Work?

### ISSUE THREAD

**Issue by metaskills** [mmanciop/opentelemetry-injector#1]
This project inspired my project (https://github.com/customink/crypteia) but I am finding out today (https://github.com/customink/crypteia/pull/19) that Python does not seem to use `getenv` which seems odd to me. Did your project work around that?

**Comment by mmanciop** [comment]
Which runtime? CPython? Jython?

For CPython, look at the autowrapt package plus a manipulation of the PYTHON_PATH env var.

**Comment by mmanciop** [comment]
@metaskills get a copy of the python binary and run `readelf -Ws` on it. It could be it uses secure_getenv instead.

**Comment by mmanciop** [comment]
Let’s move the discussion to https://github.com/customink/crypteia/pull/19#issuecomment-1235747698 :-)
